In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [11]:
df=pd.read_csv('C:\\Users\\Gautami\\OneDrive\\Desktop\\SCMS\\CN\\Assignments\\DATASETS\\karate.dat')

In [12]:
df.head()

1  2
0  1  3
1  1  4
2  1  5
3  1  6
4  1  7

In [13]:
a=np.max(df['1'])
b=np.max(df['2'])
n=max(a,b)
n

34

In [14]:
adj=np.zeros((n,n))
print(adj.shape)

(34, 34)


In [30]:
list=[]
for i in range(len(df)):
    v1=df.iloc[i][0]
    v2=df.iloc[i][1]
    adj[(v1-1),(v2-1)]=adj[(v1-1),(v2-1)]+1
    adj[(v2-1),(v1-1)]=adj[(v2-1),(v1-1)]+1

### 1.Adjacency matrix is as following for karate network

In [21]:
print(f'Adjacency matrix for karate network is as follows:\n{adj}')

Adjacency matrix for karate network is as follows:
[[0. 0. 1. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 1. 0.]
 ...
 [1. 0. 0. ... 0. 1. 1.]
 [0. 0. 1. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 1. 0.]]


#### Checking the symmetry

In [42]:
count=0
for i in range(34):
    for j in range(34):
        if adj[i,j]!=adj[j,i]:
            count=count+1
        
if count==0:
    print('The matrix is indeed symmetric.')

The matrix is indeed symmetric.


### 2. Dirgraph network

In [22]:
df2=pd.read_csv('C:\\Users\\Gautami\\OneDrive\\Desktop\\SCMS\\CN\\Assignments\\DATASETS\\dirgraph.dat')

In [23]:
df2.head()

0  3
0  0  4
1  0  6
2  1  7
3  2  5
4  2  8

In [34]:
a=np.max(df2['0'])
b=np.max(df2['3'])
n=max(a,b)
n

9

In [35]:
adj_dirg=np.zeros((n,n))
print(adj_dirg.shape)

(9, 9)


In [36]:
adj_dirg

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
for i in range(len(df2)):
    v1=df2.iloc[i][0]
    v2=df2.iloc[i][1]
    adj_dirg[(v2-1),(v1-1)]=adj_dirg[(v2-1),(v1-1)]+1

In [39]:
print(f'Adjacency matrix for dirgraph network is as follows:\n{adj_dirg}')

Adjacency matrix for dirgraph network is as follows:
[[0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0.]]


#### Checking the symmetry

In [43]:
count=0
for i in range(n):
    for j in range(n):
        if adj_dirg[i,j]!=adj_dirg[j,i]:
            count=count+1
        
if count==0:
    print('The matrix is indeed symmetric.')
else:
    print('This matrix is not symmetric.')

This matrix is not symmetric.


#### In-deg and Out-deg

In [65]:
indeg=np.zeros(n)
for i in range(n):
    for j in range(n):
        indeg[i]=indeg[i]+adj_dirg[i,j]
    

In [66]:
print(f'In-deg adjacency list using for loop is as follows:\n{indeg}')

In-deg adjacency list using for loop is as follows:
[1. 0. 1. 3. 1. 2. 3. 4. 2.]


In [67]:
indegree=np.sum(adj_dirg,axis=1)
print(f'In-deg adjacency list w/o using for loop is as follows:\n{indegree}')

In-deg adjacency list w/o using for loop is as follows:
[1. 0. 1. 3. 1. 2. 3. 4. 2.]


In [68]:
outdeg=np.sum(adj_dirg,axis=0)
print(f'Out-deg adjacency list w/o using for loop is as follows:\n{outdeg}')

Out-deg adjacency list w/o using for loop is as follows:
[1. 2. 2. 2. 2. 2. 2. 0. 4.]


In [69]:
avg_in=np.mean(indeg)
avg_in

1.8888888888888888

In [71]:
avg_out=np.mean(outdeg)
avg_out

1.8888888888888888