In [111]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [112]:
df=pd.read_csv('C:\\Users\\Gautami\\OneDrive\\Desktop\\SCMS\\CN\\Assignments\\DATASETS\\bipartite.dat')

In [113]:
df

A  a
0   A  c
1   A  f
2   A  g
3   B  b
4   B  d
5   B  f
6   C  c
7   C  e
8   C  g
9   D  a
10  D  d

In [114]:
upper=set(df['A'])
cap=list(upper)
m=len(upper)
lower=set(df['a'])
small=list(lower)
n=len(lower)

In [115]:
cap

['A', 'D', 'B', 'C']

In [116]:
small

['a', 'c', 'e', 'b', 'g', 'd', 'f']

In [117]:
adj_bip=np.zeros((m,n))
adj_bip

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [118]:
for i in range(len(df)):
    index1=cap.index(df.iloc[i][0])
    index2=small.index(df.iloc[i][1])
    adj_bip[(index1),(index2)]=adj_bip[(index1),(index2)]+1


In [119]:
print(f'Following is the incidence matrix of bipartite nerwork:\n{adj_bip}')

Following is the incidence matrix of bipartite nerwork:
[[0. 1. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1. 1.]
 [0. 1. 1. 0. 1. 0. 0.]]


In [120]:
projection=np.zeros((n,n))
projection

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [122]:
for i in range(len(df)):
    for j in range(len(df)):
        if df.iloc[i][0]==df.iloc[j][0]:
            index3=small.index(df.iloc[i][1])
            index4=small.index(df.iloc[j][1])
            projection[(index3),(index4)]=projection[(index3),(index4)]+1

In [123]:
print(f'Matrix for bipartite network with diagonal as degrees is as follows:\n{projection}')

Matrix for bipartite network with diagonal as degrees is as follows:
[[1. 0. 0. 0. 0. 1. 0.]
 [0. 2. 1. 0. 2. 0. 1.]
 [0. 1. 1. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 1. 1.]
 [0. 2. 1. 0. 2. 0. 1.]
 [1. 0. 0. 1. 0. 2. 1.]
 [0. 1. 0. 1. 1. 1. 2.]]


In [124]:
for i in range(len(small)):
    projection[i,i]=0

In [125]:
print(f'Projection matrix of vertices for bipartite network is as follows:\n{projection}')

Projection matrix of vertices for bipartite network is as follows:
[[0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 2. 0. 1.]
 [0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1.]
 [0. 2. 1. 0. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 1. 1. 1. 0.]]
